config/routes.rb
Rails.application.routes.draw do 

  resources :mining_types
  get 'welcome/index'
  get 'welcome/show'
  resources :coins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Especificar onde a rota / deve levar
  root to: 'welcome#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coin.rb
class Coin < ApplicationRecord
  belongs_to :mining_type
end

app/models/mining_type.rb
class MiningType < ApplicationRecord
  has_many :coins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :set_locale

  def set_locale
    if params[:locale]
      cookies[:locale] = params[:locale]      
    end

    if cookies[:locale]
      if I18n.locale != cookies[:locale]
        I18n.locale = cookies[:locale]
      end
    end
  end

end

app/controllers/coins_controller.rb
class CoinsController < ApplicationController
  before_action :set_coin, only: %i[ show edit update destroy ]
  before_action :set_mining_type_options, only: [:new, :create, :edit, :update]
  # GET /coins or /coins.json
  def index
    @coins = Coin.all
  end

  # GET /coins/1 or /coins/1.json
  def show
  end

  # GET /coins/new
  def new
    @coin = Coin.new
  end

  # GET /coins/1/edit
  def edit
  end

  # POST /coins or /coins.json
  def create
    @coin = Coin.new(coin_params)

    respond_to do |format|
      if @coin.save
        format.html { redirect_to @coin, notice: "Coin was successfully created." }
        format.json { render :show, status: :created, location: @coin }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coins/1 or /coins/1.json
  def update
    respond_to do |format|
      if @coin.update(coin_params)
        format.html { redirect_to @coin, notice: "Coin was successfully updated." }
        format.json { render :show, status: :ok, location: @coin }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coins/1 or /coins/1.json
  def destroy
    @coin.destroy
    respond_to do |format|
      format.html { redirect_to coins_url, notice: "Coin was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    def set_mining_type_options
      @mining_type_options = MiningType.all.pluck(:description, :id)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_coin
      @coin = Coin.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def coin_params
      params.require(:coin).permit(:description, :acronym, :url_image, :mining_type_id)
    end
end

app/controllers/mining_types_controller.rb
class MiningTypesController < ApplicationController
  before_action :set_mining_type, only: %i[ show edit update destroy ]

  # GET /mining_types or /mining_types.json
  def index
    @mining_types = MiningType.all
  end

  # GET /mining_types/1 or /mining_types/1.json
  def show
  end

  # GET /mining_types/new
  def new
    @mining_type = MiningType.new
  end

  # GET /mining_types/1/edit
  def edit
  end

  # POST /mining_types or /mining_types.json
  def create
    @mining_type = MiningType.new(mining_type_params)

    respond_to do |format|
      if @mining_type.save
        format.html { redirect_to @mining_type, notice: "Mining type was successfully created." }
        format.json { render :show, status: :created, location: @mining_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mining_types/1 or /mining_types/1.json
  def update
    respond_to do |format|
      if @mining_type.update(mining_type_params)
        format.html { redirect_to @mining_type, notice: "Mining type was successfully updated." }
        format.json { render :show, status: :ok, location: @mining_type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mining_types/1 or /mining_types/1.json
  def destroy
    @mining_type.destroy
    respond_to do |format|
      format.html { redirect_to mining_types_url, notice: "Mining type was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mining_type
      @mining_type = MiningType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mining_type_params
      params.require(:mining_type).permit(:description, :acronym)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  # layout "adm"

  def index
    cookies[:curso] = "Curso de Ruby on Rails - Jackson Pires - Cookie"
    session[:curso] = "Curso de Ruby on Rails - Jackson Pires - Session"
    @nome = ( params[:nome].present? ) ? params[:nome] : "teste"
    @curso = ( params[:curso].present? ) ? params[:curso] : "sla"
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def data_br(data_us)
    data_us.strftime("%d/%m/%Y")
  end 

  def nome_application
    "CRYPTO_WALLET"
  end
end

app/helpers/coins_helper.rb
module CoinsHelper
end

app/helpers/mining_types_helper.rb
module MiningTypesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/coins/_form.html.erb
<%= form_with(model: coin, local: true) do |form| %>

  <% if coin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(coin.errors.count, "error") %> prohibited this coin from being saved:</h2>

      <ul>
      <% coin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :description %>
    <%= form.text_field :description, class: "form-control", placeholder: "Bitcoin" %>
  </div>

  <div class="mb-3">
    <%= form.label :acronym %>
    <%= form.text_field :acronym, class: "form-control", placeholder: "BTC"  %>
  </div>

  <div class="mb-3">
    <%= form.label :mining_type_id %>
    <%= form.select("mining_type_id", @mining_type_options, {include_blank: 'selecione'}, class: "form-select" ) %>
  </div>

  <div class="mb-3">
    <%= form.label :url_image %>
    <%= form.text_field :url_image, class: "form-control", placeholder: "http://images.com/image.png"  %>
    <% if coin.url_image.present? %>
      <%= image_tag coin.url_image, width: 25, height: 25%>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit nil, class: "btn btn-primary btn-sm" %>
  </div>
  
<% end %>

app/views/coins/edit.html.erb
<h1 class="text-center"><%= t('editing.coin') %></h1>
 
<p id="notice"><%= notice %></p>

<div class="card m-4 p-2" style="width: 35rem;">
  <%= render 'form', coin: @coin %>
</div> 

<div class="p-2">
  <%= link_to t('links.show'), @coin, class: "btn btn-primary btn-sm" %> 
  <%= link_to t('links.back'), coins_path, class: "btn btn-primary btn-sm" %>
</div>

app/views/coins/index.html.erb
<div class="p-5 m-4 bg-light rounded-3">
  <div class="py-5">

    <p id="notice" class="<%= notice.present? ? '' : 'visually-hidden' %>"><%=notice%></p>

    <h1> <%= Coin.model_name.human(count: @coins.count) %> </h1> 

    <table class="table">
      <thead>
        <tr>
          <th> <%= @coins.human_attribute_name(:description) %> </th>
          <th> <%= @coins.human_attribute_name(:acronym)%></th>
          <th> <%= @coins.human_attribute_name(:url_image) %></th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @coins.each do |coin| %>
          <tr>
            <td><%= coin.description %></td>
            <td><%= coin.acronym %></td> 
            <td> <%= image_tag coin.url_image, width: 25, height: 25 %> </td>
            <td><%= link_to t('links.show'), coin, class: "btn btn-primary btn-sm"  %></td>
            <td><%= link_to t('links.edit'), edit_coin_path(coin), class: "btn btn-primary btn-sm"  %></td>
            <td><%= link_to t('links.delete'), coin, method: :delete, data: { confirm: t('messages.confirm') }, class: "btn btn-danger btn-sm" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <br>
    <%= link_to t('new.coin'), new_coin_path, class: "btn btn-primary btn-xs" %>
  </div>
</div>

app/views/coins/new.html.erb
<h1 class="text-center"><%= t('new.coin') %></h1>

<div class="card m-4 p-2" style="width: 35rem;">
  <%= render 'form', coin: @coin %>
</div>

<div class="p-2">
  <%= link_to t('links.back'), coins_path, class: "btn btn-primary btn-sm" %>
</div>

app/views/coins/show.html.erb
<p id="notice"><%= notice %></p>

<div class="card m-4" style="width: 18rem;">
  <%= image_tag(@coin.url_image, width:"50", height: "50") %>
  <div class="card-body">
    
    <h5 class="card-title"><%= @coin.acronym %></h5>
    
    <p class="card-text">
      <%= @coin.description %>
    </p>

    <hr>

    <%= link_to t('links.edit'), edit_coin_path(@coin), class: "btn btn-sm btn-primary" %> |
    <%= link_to t('links.back'), coins_path, class: "btn btn-sm btn-primary" %>
 
  </div>
</div> 

app/views/layouts/adm.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CryptoWallet admin</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h3> Admin page </h3>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CryptoWallet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    params[:controller], media: 'all', 'data-turbolinks-track': 'reload' %> 

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %> 
    <%= javascript_include_tag params[:controller], 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <%= link_to 'Crypto Wallet', root_path, class: "navbar-brand" %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item"> 
              <%= link_to 'Home', root_path, class: "nav-link active" %>
            </li> 
            <li class="nav-item">
              <%= link_to 'Português', root_path(locale: 'pt-BR'), class: "nav-link" %>
            </li> 
            <li class="nav-item">
              <%= link_to 'Inglês', root_path(locale: 'en'), class: "nav-link" %>
            </li>  
          </ul> 
        </div>
      </div>
    </nav>

    <div clas="container p-4">
      <%= yield %>
    </div>
  </body>
</html> 

app/views/mining_types/_form.html.erb
<%= form_with(model: mining_type, local: true) do |form| %>
  <% if mining_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mining_type.errors.count, "error") %> prohibited this mining_type from being saved:</h2>

      <ul>
      <% mining_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, class: "form-control", placeholder: "Proof of Work" %>
  </div>

  <div class="field">
    <%= form.label :acronym %>
    <%= form.text_field :acronym, class: "form-control", placeholder: "PoW" %>
  </div>

  <div class="actions mt-2">
    <%= form.submit nil, class: "btn btn-primary btn-sm" %>
  </div>
<% end %>

app/views/mining_types/edit.html.erb
<h1 class="text-center">Editing Mining Type</h1>


<div class="card m-4 p-2" style="width: 35rem;">
  <%= render 'form', mining_type: @mining_type %>
</div>

<div class="m-2">
  <%= link_to t('links.show'), @mining_type, class: "btn btn-sm btn-primary" %> |
  <%= link_to t('links.back'), mining_types_path, class: "btn btn-sm btn-primary" %>
</div>

app/views/mining_types/index.html.erb
<div class="p-5 m-4 bg-light rounded-3">
  <div class="py-5">

    <p id="notice" class="<%= notice.present? ? '' : 'visually-hidden' %>"><%=notice%></p>

    <h1><%= MiningType.model_name.human(count: @mining_types.count) %></h1>

    <table class="table">
      <thead>
        <tr>
          <th> <%= @mining_types.human_attribute_name(:description) %> </th>
          <th> <%= @mining_types.human_attribute_name(:acronym) %> </th> 
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @mining_types.each do |mining_type| %>
          <tr>
            <td><%= mining_type.description %></td>
            <td><%= mining_type.acronym %></td>
            <td><%= link_to 'Show', mining_type, class: "btn btn-primary btn-sm" %></td>
            <td><%= link_to 'Edit', edit_mining_type_path(mining_type), class: "btn btn-primary btn-sm" %></td>
            <td><%= link_to 'Destroy', mining_type, method: :delete, data: { confirm: t('messages.confirm') }, class: "btn btn-danger btn-sm" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to t('new.mining_type'), new_mining_type_path, class: "btn btn-primary btn-sm" %>
  </div>
</div>

app/views/mining_types/new.html.erb
<h1 class="text-center">New Mining Type</h1>

<div class="card m-4 p-2" style="width: 35rem;">
  <%= render 'form', mining_type: @mining_type %>
</div>

<div class="m-2">
  <%= link_to 'Back', mining_types_path, class: "btn btn-sm btn-primary" %>
</div>

app/views/mining_types/show.html.erb
<p id="notice"><%= notice %></p>

<div class="card m-4" style="width: 18rem;">
  <div class="card-body">
    
    <h5 class="card-title"><%= @mining_type.acronym %></h5>
    
    <p class="card-text">
      <%= @mining_type.description %>
    </p>

    <hr>

    <%= link_to 'Edit', edit_mining_type_path(@mining_type), class: "btn btn-sm btn-primary" %> |
    <%= link_to 'Back', mining_types_path, class: "btn btn-sm btn-primary" %>
 
  </div>
</div> 

app/views/welcome/_menu.erb
<%# observe http://localhost:3000/rails/info/routes %>
<%= link_to "#{Coin.model_name.human}", coins_path, class: "btn btn-primary btn-lg", role: "button" %>

<%# observe http://localhost:3000/rails/info/routes %>
<%= link_to "#{MiningType.model_name.human}", mining_types_path, class: "btn btn-primary btn-lg", role: "button"  %>

<%# Usando formatação de data %>
<%# Essa funcao data_br é uma funcao que foi criado dentro de helpers/application_helper.rb %>
<%# <p> Data <%= data_br(Date.today) </p> %>
<%# <p> Data <%= data_br(Date.today)   </p> %>

app/views/welcome/example.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

<%# criando um comment...%>

<p> A soma é :<%= 1 + 1 %> </p>

<% a = "a minha variavel a" %>

<p> Imprimindo a variavel a: <%= a %> </p>

<p> Data de hoje: <%= Date.today %></p>

app/views/welcome/index.html.erb
<div class="p-5 m-4 bg-light rounded-3">
  <div class="py-5">
    <h2 class="display-5 fw-bold"><%= t('messages.welcome') %> <%= nome_application %> </h2>
    <hr>
    <p class="col-md-12 fs-6"> <%= t('messages.welcome_option') %></p>
    <%# Renderização de partials, espécie de components %>
    <%= render "menu" %>
  </div>
</div>

app/views/welcome/show.html.erb
<h1>Welcome#show</h1>
<p>Find me in app/views/welcome/show.html.erb</p>